### ISSUE TITLE
add support for ciphertext multiply ciphertext

### ISSUE THREAD

**Issue by xnetsc** [juanelas/paillier-bignum#1]
as the title.
can add support for ciphertext multiply ciphertext,not only the "ciphertext multiply clear number"?

**Comment by juanelas** [comment]
I've uploaded a new version that should be able to multiply by a cleartext message (a big number) and not only a scalar. Multiplying by another encrypted message is not a property of the Paillier's cryptosystem, which doesn't have multiplicative homomorphism.
You can easily install the new version with npm (npm install paillier-bignum).
