### ISSUE TITLE
Trying to implement subtraction

### ISSUE THREAD

**Issue by naholyr** [juanelas/paillier-bignum#5]
I'm really not sur I'm doing it right, but I'm trying to follow [this answer](https://crypto.stackexchange.com/questions/37324/in-paillier-homomorphism-how-do-you-substract) (which seems logical to me)

![image](https://user-images.githubusercontent.com/214067/103580152-f332e200-4ed9-11eb-965d-269c36ec44f8.png)

But it doesn't work, at all:

![image](https://user-images.githubusercontent.com/214067/103580405-72281a80-4eda-11eb-9bc4-68a9903e9c34.png)

Is there something wrong in my implementation? Is the answer itself wrong? Or is this implementation not compatible with this usage?

**Comment by juanelas** [comment]
You cannot compute a multiplicative inverse with powm in bignum. Just use invertm:
```console
> const { publicKey: pub, privateKey: priv } = require('paillier-bignum').generateRandomKeys(512)
undefined
> const a = 42
undefined
> const b = 33
undefined
> const ea = pub.encrypt(a)
undefined
> const eb = pub.encrypt(b)
undefined
> priv.decrypt((ea.mul(eb))).toString()
'75'
> priv.decrypt((ea.mul(eb.invertm(pub._n2)))).toString()
'9'
> 
```

In any case I abandoned paillier-bignum in favour of paillier-bigint, which uses JS native representation for big integers (bigint), long time ago. Please consider switching to it.

```console
> const bcu = require('bigint-crypto-utils')
undefined
> const {publicKey: pub, privateKey: priv} = require('paillier-bigint').generateRandomKeysSync(512)
undefined
> const a = 42n
undefined
> const b = 33n
undefined
> const ea = pub.encrypt(a)
undefined
> const eb = pub.encrypt(b)
undefined
> priv.decrypt(ea * eb)
75n
> priv.decrypt(ea * bcu.modInv(eb, pub._n2))
9n
> 
```

**Comment by naholyr** [comment]
You absolutely rock! thanks I didn't know BigNum API, that's very clear thanks a lot!
About paillier-bigint I have to guarantee it's working on browser, I didn't check polyfills yet.

**Comment by juanelas** [comment]
paillier-bigint will work in browsers as long as you don't try to polyfill it and the browsers support ES2020 (all but the old ie, I'd say)
